### ISSUE TITLE
Explore possible getBatches and getBatch efficiencies

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#115]
This is more of an open question, but I suspect there might be more efficient ways to get batch data to the front end. Currently what happens when users open the uploads modal is: 

1. the frontend calls the `batches` query, which returns all batches that that user initiated for that particular Project. The `batch` data is pretty detailed, e.g. for a completed batch it looks something like:
```javascript
    {
          _id: 'batch-dd151987-fbc3-4df3-b287-60ac6f6a799a',
          projectId: 'jldp',
          uploadComplete: '2023-08-10T06:00:23.133+00:00',
          ingestionComplete: '2023-08-10T06:03:19.276+00:00',
          processingStart: '2023-08-10T06:03:14.525+00:00',
          processingEnd: '2023-08-10T06:14:29.096+00:00',
          overrideSerial: null,
          originalFile: 'image-dump.zip',
          total: 217,
          remaining: null,
          dead: null,
          imageErrors: null,
          errors: null
    }
```

2. Next the frontend iterates over the returned batches and makes `batches.length` number of individual calls to the `batch` query to fetch the batch details. The batch details contain all of the same fields and the only difference is that it makes the `SQS.GetQueueAttributesCommand()` calls uses that data to enrich the payloads with `batch.imageErrors`, `batch.remaining`, and `batch.dead`. So the batch detail payload for the same batch as above looks like:
```javascript
{
        _id: 'batch-dd151987-fbc3-4df3-b287-60ac6f6a799a',
        projectId: 'jldp',
        uploadComplete: '2023-08-10T06:00:23.133+00:00',
        ingestionComplete: '2023-08-10T06:03:19.276+00:00',
        processingStart: '2023-08-10T06:03:14.525+00:00',
        processingEnd: '2023-08-10T06:14:29.096+00:00',
        overrideSerial: null,
        originalFile: 'image-dump.zip',
        total: 217,
        remaining: 0,
        dead: 0,
        imageErrors: 162,
        errors: []
}
```
We then repeat this process as long as the batch upload modal is open at a polling interval of 1 min. 

I think (correct me if I'm wrong) the original idea was to reduce the # of `SQS.GetQueueAttributesCommand()`calls because they are expensive? But we're currently making those calls for all batches anyhow, even if they're not ongoing batches (I think because we need to get the `batch.imageErrors`, even if the batch is dead).

One thought is to do all of the `batch.remaining`, `batch.errors` etc enrichment for all batches returned by the `batches` query, saving ourselves all those additional round-trips to the API and batch state merging hurdles on the frontend.

If we're concerned about the cost of those calls, perhaps we create a toggle at the top of the batch table on the front end that forces users to request either "current" (ongoing) uploads or "completed" uploads, and pass that into the `batches` query as a filter? Open to any other ideas.

**Comment by ingalls** [comment]
@nathanielrindlaub Couple thoughts, but I think the action items from this ticket will probably need to be defined by what you concretely need from the frontend

- Do we currently filter to individual requests for Batch that are missing the process `processingEnd` tag? IE we don't continue to  make individual calls for batches that are done
- The addition of the `errors` property is far cheaper (in my prelim tests) than the SQS call. If we can selective filter the individual calls made to calls without a `processingEnd` or `errror.length > 0` (by adding errors to the list call) would this be a performant compromise?

Potential Actions Items
- [ ] @ingalls Adds `errors` to Batch List endpoint
- [ ] @nathanielrindlaub Tests and advises
- [ ] @ingalls reviews advice and potentially adds SQS data where possible (Where stacks do not have a processingEnd tag)

**Comment by nathanielrindlaub** [comment]
After chatting with @ingalls we landed on doing the following:

- [ ] @nathanielrindlaub will set up the upload modal to only display either the ongoing or the finished batches at once (i.e., add some kind of a toggle/switch/tab for the user to switch between them)
- [ ]  @ingalls to expose some way for the frontend to specify whether we want to fetch the current/ongoing or the completed batches and filter for them in the aggregation pipeline.
- [ ] @ingalls to move the batch `errors` and `remaining` enrichment to `getBatches`
- [ ] @ingalls to remove `getbatch` (perhaps only calculating `remaining` on batches that do not have a processingEnd)

**Comment by nathanielrindlaub** [comment]
Done :)
