### ISSUE TITLE
How to deploy locally? Windows11

### ISSUE THREAD

**Issue by devboit** [tnc-ca-geo/animl-api#151]
Can the project be deployed to Windows 11? How to deploy locally, following the Readme operation seems to be ineffective

**Comment by nathanielrindlaub** [comment]
Hey @devboit - I have never attempted do run the app locally on a Windows machine, so I'm not sure if/how the setup would differ. I'm not super familiar with Windows-based development in general, so I'm afraid I probably won't be much use here. 

Can I ask what you're trying to accomplish by getting it running locally? It's really a cloud-based app that's configured to run specifically on AWS infrastructure.

**Comment by devboit** [comment]
Thank you for your reply. I would like to try running it locally because I am using the Windows operating system and I am using VScode to open the project. Additionally, do I need to deploy animl API, animl frontend, and animl ingest for our project? Deploying it is a bit difficult for me. Can you provide me with a trial account? I would like to log in and experience it. Thank you

**Comment by nathanielrindlaub** [comment]
@devboit I am happy to talk about getting you set up a with trial account, but we have some restrictions on who can use the app and for what purpose so I'd have to learn more about your goals and interest. Do you have an email address I can reach you at to continue this conversation?

**Comment by devboit** [comment]
Of course, my email address is fanerboit@163.com We are a company conducting research on wildlife. We attempt to use infrared cameras to capture images and videos of wildlife for AI recognition, and then collect information on wildlife species for research reports. We hope to meet your company's trial requirements, and I am eager to try out your system

**Comment by nathanielrindlaub** [comment]
Ok excellent, I'll follow up with you via email!
