### ISSUE TITLE
Get batch PR to pass unit test

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#95]
@ingalls, just making a note here that animl-api is failing its unit test & I'm not super sure how to reason about it.

**Comment by ingalls** [comment]
Per voice, this test was failing before this phase of work. Initial thoughts are
- Migrate to AWS-SDK@3
- Use Sinon for unit testing - the mapbox mocks were for V2 of the API
If we get an initial phase/partial block of work we'll add this to the bucket list of TODO items.

**Comment by nathanielrindlaub** [comment]
@ingalls it looks like the latest PR (#102) is passing now? Can I close this out?
