### ISSUE TITLE
Support duplicate image occurrences in different projects?

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#98]
I'm not sure how critical this is... but supporting duplicate images across multiple projects is going to be tough b/c MongoDB collections always have a unique index on `_id`, which we set by hashing the whole image file in the ingest-image Lambda. One idea would be to include the images' project ID as an additional input for the hashing algo, but we don't know what project an image belongs to at the ingest-image stage...

**Comment by ingalls** [comment]
@nathanielrindlaub One thought that would partially resolve this would be to include a BatchID as a prefix on the image id if the image were part of a Batch. This would allow the following:
- Duplicate Images accross different batches
- Duplicate images between individual uploads & batches

It would not allow duplicate images for individual uploads - however Batch Prefix for batches and a Date Prefix for individual uploads (Unix Epoch?) could accomplish this as well if it were desired.
